name: Compilar y Probar

on:
  pull_request:
    branches:
      - main

env:
  DOTNET_VERSION: '8'          

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Obteniendo el codigo
        uses: actions/checkout@v4.2.2

      - name: Instalar .NET
        uses: actions/setup-dotnet@v4.1.0
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Obteniendo las dependencias
        run: dotnet restore

      - name: Compilar
        run: dotnet build --no-restore

      - name: Realizar pruebas
        run: dotnet test --no-build
