name: No se

env:
  AZURE_WEBAPP_NAME: GithubActionsDemoApp    # set this to the name of your Azure Web App
  AZURE_WEBAPP_PACKAGE_PATH: '.'      # set this to the path to your web app project, defaults to the repository root
  DOTNET_VERSION: '8'                 # set this to the .NET Core version to use

on: 
  push:
    paths:
      - ".github/workflows/main.yml"
      - "GithubActionsDemoApp/**"
      - "Pruebas/**"
  workflow_dispatch:

jobs:
  build:
    permissions:
      contents: write
    env:
      proyecto: GithubActionsDemoApp/GithubActionsDemoApp.csproj
    runs-on: ubuntu-latest
    steps:
      - name: Obteniendo el codigo
        uses: actions/checkout@v4.2.2

      - name: Instalar .NET
        uses: actions/setup-dotnet@v4.1.0
        with:
          dotnet-version: 8.0.x

      - name: Obteniendo las dependencias
        run: dotnet restore

      - name: Compilar
        run: dotnet build --no-restore

      - name: Realizar pruebas
        run: dotnet test --no-build

      - run: ls

      - name: dotnet publish
        run: dotnet publish $proyecto -c Release -o myapp --runtime win-x86

      - run: ls

      - uses: actions/upload-artifact@v4.4.3
        with:
          path: ./myapp
          name: build

      - name: Zip
        if: startsWith(github.ref, 'refs/tags/')
        run: zip -r mi_app.zip ./myapp

      - uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ./mi_app.zip
          body: "Nuestra aplicacion"
          tag_name: ${{ github.ref_name }}

  deploy:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build
    steps:
      - run: ls
      
      - name: obtener los artefactos
        uses: actions/download-artifact@v4.1.8
        with:
          name: build

      - run: ls

      - name: desplegar a Azure
        uses: Azure/webapps-deploy@v3.0.1
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./myapp
        
      
