name: No se

on: 
  workflow_dispatch:

jobs:
  build:
    permissions:
      contents: write
    env:
      proyecto: GithubActionsDemoApp/GithubActionsDemoApp.csproj
    runs-on: ubuntu-latest
    steps:
      - name: Obteniendo el codigo
        uses: actions/checkout@v4.2.2

      - name: Instalar .NET
        uses: actions/setup-dotnet@v4.1.0
        with:
          dotnet-version: 8.0.x

      - name: Obteniendo las dependencias
        run: dotnet restore

      - name: Compilar
        run: dotnet build --no-restore

      - name: Realizar pruebas
        run: dotnet test --no-build

      - run: ls

      - name: dotnet publish
        run: dotnet publish $proyecto -c Release -o myapp --runtime win-x86

      - run: ls

      - uses: actions/upload-artifact@v4.4.3
        with:
          path: ./myapp
          name: build

      - name: Zip
        run: zip -r mi_app.zip ./myapp

      - uses: softprops/action-gh-release@v2
        with:
          files: ./mi_app.zip
          body: "Nuestra aplicacion"
          tag_name: ${{ github.ref_name }}
